#!/usr/bin/env python3
"""
Phase 3.5: Pack Tasks — bundle each candidate into a self-contained task file.

Reads candidates.json + crawled snippets → writes data/v9/tasks/{content_slug}.json.
Each task file contains everything needed for an isolated content-generation agent:
  - candidate metadata (topic, angle, reason)
  - writer prompt
  - source material (crawled snippets)
  - API config (endpoint, topicSlug)

The content_slug is generated by the LLM during candidate selection and serves
as both the task filename and the final content slug POSTed to the API.

Usage:
  python3 -m pipeline.pack_tasks
  python3 -m pipeline.pack_tasks --dry-run
"""

import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

from .config import (
    CANDIDATES_FILE, SNIPPETS_DIR, V9_DIR, DIRECTIVES_FILE,
    ensure_dirs, load_json, get_api_url, get_api_key,
)
from .eir_config import SKILL_DIR

TASKS_DIR = V9_DIR / "tasks"
WRITER_PROMPT_PATH = SKILL_DIR / "references" / "writer-prompt-eir.md"
MIN_CONTENT_LEN = 500


def extract_article_body(text, max_len=4000):
    """Extract the article body from crawled content, skipping nav/boilerplate.

    Strategy:
    - Skip image links, markdown link lists, short fragments, nav-like lines.
    - Find the first substantial paragraph (40+ chars of real text).
    - Return up to max_len chars of the article body.
    """
    if not text:
        return ""

    lines = text.split("\n")
    body_start = 0

    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped:
            continue
        # Skip image-only lines: ![...](...)  or plain URLs
        if stripped.startswith("![") or stripped.startswith("http"):
            continue
        # Skip markdown link lists: * [...], - [...], * [![
        if re.match(r'^[\*\-]\s*\[', stripped):
            continue
        # Skip lines that are mostly links/markdown formatting
        plain = re.sub(r'\[([^\]]*?)\]\([^)]*\)', r'\1', stripped)
        plain = re.sub(r'[!\[\]()#*_`>\-]', '', plain).strip()
        if len(plain) < 40:
            continue
        # Found a substantial line — this is likely the article start
        body_start = i
        break

    # Include the heading before if present
    if body_start > 0 and lines[body_start - 1].strip().startswith("#"):
        body_start -= 1

    body = "\n".join(lines[body_start:])
    return body[:max_len]


def snippet_path_for_url(url):
    url_hash = hashlib.md5(url.encode()).hexdigest()[:12]
    return SNIPPETS_DIR / ("%s.json" % url_hash)


def _get_title_for_url(candidate, url):
    titles = candidate.get("source_titles", [])
    urls = candidate.get("source_urls", [])
    if isinstance(titles, dict):
        return titles.get(url, "")
    if isinstance(titles, list) and isinstance(urls, list):
        try:
            idx = urls.index(url)
            return titles[idx] if idx < len(titles) else ""
        except ValueError:
            return ""
    return ""


def load_candidate_sources(candidate):
    """Load crawled content for a candidate's source URLs."""
    sources = []
    # Get source_dates from candidate (written by crawl.py freshness gate)
    source_dates = candidate.get("source_dates", {})
    for url in candidate.get("crawled_sources", candidate.get("source_urls", [])):
        path = snippet_path_for_url(url)
        if not path.exists():
            continue
        snippet = load_json(path)
        content = snippet.get("content", "")
        if len(content) < MIN_CONTENT_LEN:
            continue
        # Get publishedDate: snippet first, then fallback to source_dates
        pub_date = snippet.get("publishedDate")
        if not pub_date and url in source_dates:
            pub_date = source_dates[url].get("publishedDate")
        sources.append({
            "url": url,
            "title": _get_title_for_url(candidate, url),
            "name": urlparse(url).netloc.replace("www.", ""),
            "content": content[:6000],
            "publishedDate": pub_date,
        })
    return sources


def load_writer_prompt():
    """Load writer prompt from references/writer-prompt-eir.md."""
    if WRITER_PROMPT_PATH.exists():
        return WRITER_PROMPT_PATH.read_text()
    return "Generate content for Eir. Output JSON only."


def sanitize_slug(slug):
    """Sanitize a content slug for use as filename."""
    slug = slug.lower().strip()
    slug = re.sub(r'[^a-z0-9-]', '-', slug)
    slug = re.sub(r'-+', '-', slug).strip('-')
    return slug[:80]  # reasonable max length


def pack_single_task(candidate, sources, writer_prompt, directives_map):
    """Build a self-contained task bundle for one candidate."""
    topic_slug = candidate["matched_topic_slug"]
    content_slug = candidate.get("content_slug", "")
    if not content_slug:
        # Fallback: use topic_slug + angle hash
        angle = candidate.get("suggested_angle", "")
        angle_hash = hashlib.md5(angle.encode()).hexdigest()[:6]
        content_slug = "%s_%s" % (topic_slug, angle_hash)

    content_slug = sanitize_slug(content_slug)
    directive = directives_map.get(topic_slug, {})

    # Build source material text for the prompt
    source_text = ""
    source_meta = []
    for i, s in enumerate(sources):
        source_text += "\n--- Source %d: %s (%s) ---\n%s\n" % (
            i + 1, s["title"], s["name"], extract_article_body(s["content"], 4000))
        source_meta.append({
            "url": s["url"],
            "title": s["title"],
            "name": s["name"],
            "publishedDate": s.get("publishedDate"),
        })

    task = {
        "task_version": 1,
        "content_slug": content_slug,
        "topic_slug": topic_slug,
        "topic_name": directive.get("label") or directive.get("topic", topic_slug),
        "suggested_angle": candidate.get("suggested_angle", ""),
        "reason": candidate.get("reason", ""),
        "priority": candidate.get("priority", "medium"),
        "source_meta": source_meta,
        "source_text": source_text,
        "writer_prompt": writer_prompt,
        "has_fresh_source": candidate.get("has_fresh_source", True),
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    return task


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Pack Tasks")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    ensure_dirs()
    TASKS_DIR.mkdir(parents=True, exist_ok=True)
    print("📦 Pack Tasks")

    # Load candidates
    candidates = load_json(CANDIDATES_FILE, {})
    candidate_list = candidates.get("candidates", [])
    if not candidate_list:
        print("  ❌ No candidates in candidates.json")
        sys.exit(1)

    # Load directives
    directives_data = load_json(DIRECTIVES_FILE, {})
    all_directives = directives_data.get("directives", []) + directives_data.get("tracked", [])
    directives_map = {d["slug"]: d for d in all_directives}

    # Load writer prompt once
    writer_prompt = load_writer_prompt()
    print("  Writer prompt: %d chars" % len(writer_prompt))

    # Load used URLs for dedup
    try:
        from .run_state import get_all_used_urls, get_posted_topic_slugs
        used_urls = get_all_used_urls()
        posted_topics = get_posted_topic_slugs()
    except Exception:
        used_urls = set()
        posted_topics = set()

    # Pack each candidate into a task
    packed = 0
    skipped = 0
    for c in candidate_list:
        topic = c.get("matched_topic_slug", "")
        content_slug = c.get("content_slug", "")

        # Skip if no content
        if not c.get("has_content", False):
            print("  ⏭️  %s: no crawled content" % topic)
            skipped += 1
            continue

        # Skip if freshness gate failed
        if not c.get("has_fresh_source", True):
            print("  ⏭️  %s: no fresh source" % topic)
            skipped += 1
            continue

        # Skip if topic already posted today
        if topic in posted_topics:
            print("  ⏭️  %s: already posted today" % topic)
            skipped += 1
            continue

        # Skip if ALL source URLs already used
        source_urls = c.get("source_urls", [])
        fresh_urls = [u for u in source_urls if u not in used_urls]
        if source_urls and not fresh_urls:
            print("  ⏭️  %s: all source URLs already used" % topic)
            skipped += 1
            continue

        # Load sources
        sources = load_candidate_sources(c)
        if not sources:
            print("  ⏭️  %s: no usable sources after crawl" % topic)
            skipped += 1
            continue

        # Build task
        task = pack_single_task(c, sources, writer_prompt, directives_map)
        slug = task["content_slug"]

        if args.dry_run:
            print("  [dry-run] Would pack: %s.json (%d sources, %d chars)" % (
                slug, len(sources), len(task["source_text"])))
            packed += 1
            continue

        # Write task file
        task_path = TASKS_DIR / ("%s.json" % slug)
        task_path.write_text(json.dumps(task, indent=2, ensure_ascii=False))
        print("  ✅ %s.json (%d sources, angle: %s)" % (
            slug, len(sources), task["suggested_angle"][:50]))
        packed += 1

    print("\n📦 Packed %d tasks, skipped %d" % (packed, skipped))
    if packed > 0 and not args.dry_run:
        # Write manifest
        manifest = {
            "packed_at": datetime.now(timezone.utc).isoformat(),
            "task_count": packed,
            "skipped": skipped,
            "tasks": sorted([f.stem for f in TASKS_DIR.glob("*.json") if f.stem != "manifest"]),
        }
        (TASKS_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2))
        print("  Manifest: %s" % (TASKS_DIR / "manifest.json"))


if __name__ == "__main__":
    main()
